// <auto-generated />
using System;
using HackathonBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HackathonBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HackathonBackend.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HackathonBackend.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("HackathonBackend.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("HackathonBackend.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("boolean");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pain Relief",
                            Composition = "Paracetamol 650mg",
                            Description = "Effective relief from fever and mild to moderate pain.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
                            Manufacturer = "Micro Labs",
                            Name = "Dolo 650",
                            PackagingType = "Strip of 15",
                            Price = 35m,
                            RequiresPrescription = false,
                            StockQuantity = 250,
                            Strength = "650mg"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pain Relief",
                            Composition = "Paracetamol 500mg",
                            Description = "Fast-acting fever and headache relief.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
                            Manufacturer = "GSK",
                            Name = "Crocin Advance",
                            PackagingType = "Strip of 15",
                            Price = 30m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Allergy",
                            Composition = "Cetirizine HCl 10mg",
                            Description = "Antihistamine for allergic rhinitis and skin allergies.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "Cipla",
                            Name = "Cetirizine 10mg",
                            PackagingType = "Strip of 10",
                            Price = 25m,
                            RequiresPrescription = false,
                            StockQuantity = 300,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Antibiotic",
                            Composition = "Amoxicillin Trihydrate 500mg",
                            Description = "Broad-spectrum antibiotic for bacterial infections.",
                            DosageForm = "Capsule",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "Cipla",
                            Name = "Amoxicillin 500mg",
                            PackagingType = "Strip of 10",
                            Price = 85m,
                            RequiresPrescription = true,
                            StockQuantity = 150,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Antibiotic",
                            Composition = "Azithromycin 500mg",
                            Description = "Macrolide antibiotic for respiratory and skin infections.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400",
                            Manufacturer = "Sun Pharma",
                            Name = "Azithromycin 500mg",
                            PackagingType = "Strip of 3",
                            Price = 110m,
                            RequiresPrescription = true,
                            StockQuantity = 120,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pain Relief",
                            Composition = "Ibuprofen 400mg",
                            Description = "Anti-inflammatory pain reliever.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Abbott",
                            Name = "Ibuprofen 400mg",
                            PackagingType = "Strip of 10",
                            Price = 40m,
                            RequiresPrescription = false,
                            StockQuantity = 220,
                            Strength = "400mg"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Gastro",
                            Composition = "Pantoprazole Sodium 40mg",
                            Description = "Proton pump inhibitor for acidity and ulcers.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
                            Manufacturer = "Sun Pharma",
                            Name = "Pantoprazole 40mg",
                            PackagingType = "Strip of 15",
                            Price = 90m,
                            RequiresPrescription = false,
                            StockQuantity = 180,
                            Strength = "40mg"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Gastro",
                            Composition = "Omeprazole 20mg",
                            Description = "Reduces stomach acid production.",
                            DosageForm = "Capsule",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Dr. Reddy's",
                            Name = "Omeprazole 20mg",
                            PackagingType = "Strip of 10",
                            Price = 75m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "20mg"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Diabetes",
                            Composition = "Metformin HCl 500mg",
                            Description = "First-line therapy for type 2 diabetes.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "USV",
                            Name = "Metformin 500mg",
                            PackagingType = "Strip of 15",
                            Price = 50m,
                            RequiresPrescription = true,
                            StockQuantity = 250,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Diabetes",
                            Composition = "Glimepiride 2mg",
                            Description = "Sulfonylurea for type 2 diabetes control.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Sanofi",
                            Name = "Glimepiride 2mg",
                            PackagingType = "Strip of 10",
                            Price = 95m,
                            RequiresPrescription = true,
                            StockQuantity = 140,
                            Strength = "2mg"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Cardiac",
                            Composition = "Atorvastatin Calcium 10mg",
                            Description = "Statin to lower cholesterol.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "Pfizer",
                            Name = "Atorvastatin 10mg",
                            PackagingType = "Strip of 10",
                            Price = 120m,
                            RequiresPrescription = true,
                            StockQuantity = 160,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Cardiac",
                            Composition = "Amlodipine Besilate 5mg",
                            Description = "Calcium channel blocker for hypertension.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "Cipla",
                            Name = "Amlodipine 5mg",
                            PackagingType = "Strip of 10",
                            Price = 60m,
                            RequiresPrescription = true,
                            StockQuantity = 180,
                            Strength = "5mg"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Cardiac",
                            Composition = "Telmisartan 40mg",
                            Description = "Angiotensin II receptor blocker for BP.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Glenmark",
                            Name = "Telmisartan 40mg",
                            PackagingType = "Strip of 10",
                            Price = 105m,
                            RequiresPrescription = true,
                            StockQuantity = 150,
                            Strength = "40mg"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Vitamins",
                            Composition = "Ascorbic Acid 500mg",
                            Description = "Antioxidant immunity booster.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "HealthVit",
                            Name = "Vitamin C 500mg",
                            PackagingType = "Bottle of 60",
                            Price = 150m,
                            RequiresPrescription = false,
                            StockQuantity = 300,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Vitamins",
                            Composition = "Cholecalciferol 60000 IU",
                            Description = "Weekly Vitamin D supplement.",
                            DosageForm = "Capsule",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
                            Manufacturer = "Mankind",
                            Name = "Vitamin D3 60K",
                            PackagingType = "Strip of 4",
                            Price = 130m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "60000 IU"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Vitamins",
                            Composition = "Methylcobalamin 1500mcg",
                            Description = "Nerve health and energy support.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Zydus",
                            Name = "Vitamin B12 1500mcg",
                            PackagingType = "Strip of 10",
                            Price = 80m,
                            RequiresPrescription = false,
                            StockQuantity = 220,
                            Strength = "1500mcg"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Vitamins",
                            Composition = "Calcium Carbonate 500mg + D3 250IU",
                            Description = "Bone health supplement.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Shelcal",
                            Name = "Calcium + Vit D3",
                            PackagingType = "Strip of 15",
                            Price = 110m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Vitamins",
                            Composition = "Multivitamins + Minerals",
                            Description = "Daily wellness supplement.",
                            DosageForm = "Capsule",
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
                            Manufacturer = "Revital H",
                            Name = "Multivitamin Daily",
                            PackagingType = "Bottle of 30",
                            Price = 220m,
                            RequiresPrescription = false,
                            StockQuantity = 180,
                            Strength = "Multi"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cough & Cold",
                            Composition = "Diphenhydramine + Ammonium Chloride",
                            Description = "Cough syrup for dry and wet cough.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "J&J",
                            Name = "Benadryl Syrup",
                            PackagingType = "Bottle 100ml",
                            Price = 95m,
                            RequiresPrescription = false,
                            StockQuantity = 160,
                            Strength = "100ml"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cough & Cold",
                            Composition = "Herbal blend",
                            Description = "Ayurvedic cough relief.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "Dabur",
                            Name = "Honitus Cough Syrup",
                            PackagingType = "Bottle 100ml",
                            Price = 85m,
                            RequiresPrescription = false,
                            StockQuantity = 180,
                            Strength = "100ml"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Cough & Cold",
                            Composition = "Paracetamol + Phenylephrine + CPM",
                            Description = "Multi-symptom cold and flu relief.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Centaur",
                            Name = "Sinarest",
                            PackagingType = "Strip of 10",
                            Price = 55m,
                            RequiresPrescription = false,
                            StockQuantity = 220,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Cough & Cold",
                            Composition = "Paracetamol + Phenylephrine + Caffeine",
                            Description = "Cold, flu, and headache relief.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Reckitt",
                            Name = "D-Cold Total",
                            PackagingType = "Strip of 10",
                            Price = 50m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Cough & Cold",
                            Composition = "Camphor + Menthol + Eucalyptus",
                            Description = "Topical cold relief balm.",
                            DosageForm = "Ointment",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "P&G",
                            Name = "Vicks VapoRub",
                            PackagingType = "Jar 50g",
                            Price = 100m,
                            RequiresPrescription = false,
                            StockQuantity = 240,
                            Strength = "50g"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Hydration",
                            Composition = "Glucose + Salts",
                            Description = "Rehydration salts for diarrhoea.",
                            DosageForm = "Powder",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
                            Manufacturer = "Electral",
                            Name = "ORS Powder",
                            PackagingType = "Sachet",
                            Price = 22m,
                            RequiresPrescription = false,
                            StockQuantity = 400,
                            Strength = "21.8g"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Gastro",
                            Composition = "Sodium Bicarbonate + Citric Acid",
                            Description = "Fast acidity and gas relief.",
                            DosageForm = "Powder",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
                            Manufacturer = "GSK",
                            Name = "Eno Fruit Salt",
                            PackagingType = "Sachet",
                            Price = 10m,
                            RequiresPrescription = false,
                            StockQuantity = 500,
                            Strength = "5g"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Gastro",
                            Composition = "Magaldrate + Simethicone",
                            Description = "Antacid and anti-flatulent.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "Abbott",
                            Name = "Digene Gel",
                            PackagingType = "Bottle 200ml",
                            Price = 130m,
                            RequiresPrescription = false,
                            StockQuantity = 160,
                            Strength = "200ml"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Gastro",
                            Composition = "Loperamide HCl 2mg",
                            Description = "For acute diarrhoea.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Cipla",
                            Name = "Loperamide 2mg",
                            PackagingType = "Strip of 10",
                            Price = 30m,
                            RequiresPrescription = false,
                            StockQuantity = 300,
                            Strength = "2mg"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Gastro",
                            Composition = "Ondansetron 4mg",
                            Description = "Anti-emetic for nausea and vomiting.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Glenmark",
                            Name = "Ondansetron 4mg",
                            PackagingType = "Strip of 10",
                            Price = 70m,
                            RequiresPrescription = true,
                            StockQuantity = 180,
                            Strength = "4mg"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Allergy",
                            Composition = "Montelukast + Levocetirizine",
                            Description = "Allergy and asthma management.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "Cipla",
                            Name = "Montair LC",
                            PackagingType = "Strip of 10",
                            Price = 145m,
                            RequiresPrescription = true,
                            StockQuantity = 150,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Allergy",
                            Composition = "Levocetirizine 5mg",
                            Description = "Non-sedating antihistamine.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Dr. Reddy's",
                            Name = "Levocetirizine 5mg",
                            PackagingType = "Strip of 10",
                            Price = 40m,
                            RequiresPrescription = false,
                            StockQuantity = 260,
                            Strength = "5mg"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Respiratory",
                            Composition = "Salbutamol 100mcg",
                            Description = "Quick relief bronchodilator.",
                            DosageForm = "Inhaler",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Cipla",
                            Name = "Asthalin Inhaler",
                            PackagingType = "Inhaler 200 doses",
                            Price = 175m,
                            RequiresPrescription = true,
                            StockQuantity = 100,
                            Strength = "100mcg"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Respiratory",
                            Composition = "Budesonide 200mcg",
                            Description = "Steroid inhaler for asthma control.",
                            DosageForm = "Inhaler",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Cipla",
                            Name = "Budecort Inhaler",
                            PackagingType = "Inhaler 200 doses",
                            Price = 320m,
                            RequiresPrescription = true,
                            StockQuantity = 80,
                            Strength = "200mcg"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Supplements",
                            Composition = "Iron + Folic Acid",
                            Description = "Anaemia support tonic.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Dexorange",
                            Name = "Iron + Folic Acid",
                            PackagingType = "Bottle 200ml",
                            Price = 175m,
                            RequiresPrescription = false,
                            StockQuantity = 140,
                            Strength = "200ml"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Supplements",
                            Composition = "Multivitamins + Zinc",
                            Description = "Multivitamin with zinc.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Apex",
                            Name = "Zincovit Tablet",
                            PackagingType = "Strip of 15",
                            Price = 95m,
                            RequiresPrescription = false,
                            StockQuantity = 220,
                            Strength = "Multi"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Supplements",
                            Composition = "B-Complex + C",
                            Description = "B-complex supplement.",
                            DosageForm = "Capsule",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Pfizer",
                            Name = "Becosules Capsules",
                            PackagingType = "Strip of 20",
                            Price = 60m,
                            RequiresPrescription = false,
                            StockQuantity = 280,
                            Strength = "Multi"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Gastro",
                            Composition = "Ranitidine 150mg",
                            Description = "H2 blocker for acidity.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "GSK",
                            Name = "Ranitidine 150mg",
                            PackagingType = "Strip of 10",
                            Price = 35m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "150mg"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Pain Relief",
                            Composition = "Diclofenac Diethylamine 1.16%",
                            Description = "Topical pain relief gel.",
                            DosageForm = "Gel",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Volini",
                            Name = "Diclofenac Gel",
                            PackagingType = "Tube 30g",
                            Price = 110m,
                            RequiresPrescription = false,
                            StockQuantity = 260,
                            Strength = "30g"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Pain Relief",
                            Composition = "Methyl Salicylate + Menthol",
                            Description = "Backache and muscle relief spray.",
                            DosageForm = "Spray",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "Reckitt",
                            Name = "Moov Spray",
                            PackagingType = "Spray Can 55g",
                            Price = 175m,
                            RequiresPrescription = false,
                            StockQuantity = 140,
                            Strength = "55g"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Cough & Cold",
                            Composition = "Sodium Chloride 0.9%",
                            Description = "Gentle nasal congestion relief.",
                            DosageForm = "Drops",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
                            Manufacturer = "Nasivion",
                            Name = "Saline Nasal Drops",
                            PackagingType = "Bottle 10ml",
                            Price = 70m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "10ml"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Cough & Cold",
                            Composition = "Xylometazoline 0.1%",
                            Description = "Decongestant nasal spray.",
                            DosageForm = "Spray",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "GSK",
                            Name = "Otrivin Nasal Spray",
                            PackagingType = "Bottle 10ml",
                            Price = 105m,
                            RequiresPrescription = false,
                            StockQuantity = 180,
                            Strength = "10ml"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Antibiotic",
                            Composition = "Ciprofloxacin 500mg",
                            Description = "Broad-spectrum antibiotic.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400",
                            Manufacturer = "Cipla",
                            Name = "Ciplox 500mg",
                            PackagingType = "Strip of 10",
                            Price = 90m,
                            RequiresPrescription = true,
                            StockQuantity = 130,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Antibiotic",
                            Composition = "Amoxicillin + Clavulanic Acid",
                            Description = "Combination antibiotic.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400",
                            Manufacturer = "GSK",
                            Name = "Augmentin 625",
                            PackagingType = "Strip of 6",
                            Price = 240m,
                            RequiresPrescription = true,
                            StockQuantity = 100,
                            Strength = "625mg"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Thyroid",
                            Composition = "Levothyroxine 50mcg",
                            Description = "Hypothyroidism therapy.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "Abbott",
                            Name = "Thyronorm 50mcg",
                            PackagingType = "Strip of 100",
                            Price = 145m,
                            RequiresPrescription = true,
                            StockQuantity = 160,
                            Strength = "50mcg"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Gastro",
                            Composition = "Liquid Paraffin + Milk of Magnesia",
                            Description = "Laxative for constipation.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "Abbott",
                            Name = "Cremaffin Plus",
                            PackagingType = "Bottle 225ml",
                            Price = 165m,
                            RequiresPrescription = false,
                            StockQuantity = 140,
                            Strength = "225ml"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Pediatric",
                            Composition = "Paracetamol 250mg/5ml",
                            Description = "Child fever and pain syrup.",
                            DosageForm = "Syrup",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
                            Manufacturer = "P&G",
                            Name = "Pediatric Paracetamol Syrup",
                            PackagingType = "Bottle 60ml",
                            Price = 65m,
                            RequiresPrescription = false,
                            StockQuantity = 220,
                            Strength = "60ml"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Pediatric",
                            Composition = "Multivitamin drops",
                            Description = "Daily drops for children.",
                            DosageForm = "Drops",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
                            Manufacturer = "Pfizer",
                            Name = "Pediatric Multivitamin Drops",
                            PackagingType = "Bottle 15ml",
                            Price = 95m,
                            RequiresPrescription = false,
                            StockQuantity = 200,
                            Strength = "15ml"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Diabetes",
                            Composition = "Insulin Glargine",
                            Description = "Long-acting basal insulin.",
                            DosageForm = "Injection",
                            ImageUrl = "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
                            Manufacturer = "Sanofi",
                            Name = "Insulin Glargine 100IU",
                            PackagingType = "Cartridge 3ml",
                            Price = 850m,
                            RequiresPrescription = true,
                            StockQuantity = 60,
                            Strength = "100IU/ml"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Cardiac",
                            Composition = "Aspirin 75mg",
                            Description = "Low-dose aspirin antiplatelet.",
                            DosageForm = "Tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
                            Manufacturer = "USV",
                            Name = "Ecosprin 75mg",
                            PackagingType = "Strip of 14",
                            Price = 14m,
                            RequiresPrescription = true,
                            StockQuantity = 320,
                            Strength = "75mg"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Personal Care",
                            Composition = "Ethanol 70%",
                            Description = "Kills 99.9% germs.",
                            DosageForm = "Liquid",
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
                            Manufacturer = "Dettol",
                            Name = "Hand Sanitizer 500ml",
                            PackagingType = "Bottle 500ml",
                            Price = 199m,
                            RequiresPrescription = false,
                            StockQuantity = 300,
                            Strength = "500ml"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Personal Care",
                            Composition = "3-ply mask",
                            Description = "Disposable surgical face masks.",
                            DosageForm = "Mask",
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
                            Manufacturer = "Generic",
                            Name = "Surgical Face Mask (50)",
                            PackagingType = "Box of 50",
                            Price = 150m,
                            RequiresPrescription = false,
                            StockQuantity = 400,
                            Strength = "3-ply"
                        });
                });

            modelBuilder.Entity("HackathonBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionFile")
                        .HasColumnType("text");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HackathonBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HackathonBackend.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionCode")
                        .IsUnique();

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "10% off your order",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 200m,
                            MinimumOrderValue = 0m,
                            PromotionCode = "WELCOME10",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Flat ₹50 off on orders above ₹500",
                            DiscountType = "FixedAmount",
                            DiscountValue = 50m,
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinimumOrderValue = 500m,
                            PromotionCode = "FLAT50",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("HackathonBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@bytebrigade.local",
                            FirstName = "Admin",
                            LastName = "User",
                            LoyaltyPoints = 0,
                            Password = "admin123",
                            PhoneNumber = "0000000000",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HackathonBackend.Models.CartItem", b =>
                {
                    b.HasOne("HackathonBackend.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HackathonBackend.Models.OrderItem", b =>
                {
                    b.HasOne("HackathonBackend.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackathonBackend.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HackathonBackend.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
